const fs=require('fs'),vm=require('vm'),assert=require('assert');
const {webcrypto}=require('crypto');
const source=fs.readFileSync('static/wordpress.js','utf8');
const good={endpoint:'https://site.example/wp-json/fontready/v1/fonts',status:'https://site.example/wp-json/fontready/v1/connection',site:'https://site.example/',key:'a'.repeat(64),expires:Math.floor(Date.now()/1000)+3600};
function setup({preview=false,expired=false,code=200,connection=good,callback=null,elementor=false,kit=null,failAt=null,timeout=false,offline=false,malformed=null,chunked=false,payloadSize=0,failOnce=false}={}){
 const nodes={};for(const id of ['wordpress-publish','wordpress-status','wordpress-site','wordpress-pro','wordpress-connect','wordpress-plugin','website-confirmation','elementor-manage','result','connection-status','wordpress-disconnect','elementor-progress'])nodes[id]={value:'',checked:false,disabled:false,textContent:'',className:'',hidden:false,scrollIntoView(){}};
 const saved=new Map();if(connection)saved.set('fontready.website.v3',JSON.stringify(connection));saved.set('fontready.requested-site','https://site.example/');
 if(kit){saved.set('fontready.selected-kit',kit);saved.set('fontready.pending-publish',kit);}
 const calls=[],listeners={};let failedOnce=false;const context={window:{fontreadyCallback:callback,addEventListener:(name,fn)=>listeners[name]=fn},sessionStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v),removeItem:k=>saved.delete(k)},history:{replaceState(){}},location:{href:'https://fontready.com/font-to-elementor-pro/'+(kit?'?kit='+kit:''),assign(url){calls.push({kind:'navigate',url})}},document:{body:{dataset:{elementor:elementor?'true':'false'}},getElementById:id=>nodes[id]},previewOnly:preview,activeJob:{id:'test',state:'ready',expires_at:new Date(Date.now()+(expired?-1000:60000)).toISOString()},Date,URL,AbortSignal,JSON,Number,Array,Error,TextEncoder,Uint8Array,String,crypto:webcrypto,btoa,navigator:{onLine:!offline},csrf:()=> 'csrf',api:async(path,options)=>{calls.push({kind:'api',path,options});if(path.endsWith('/complete/'))return {job:kit};if(path.startsWith('/api/conversions/')&&!options)return {id:kit,state:'ready',expires_at:new Date(Date.now()+60000).toISOString(),results:[]};return path.includes('connect/')?{url:'https://site.example/wp-admin/admin.php?page=fontready'}:{version:1,fonts:[],padding:'x'.repeat(payloadSize)}},fetch:async(path,options)=>{calls.push({kind:'wp',path,options});const part=options.body?JSON.parse(options.body):null;const phase=path.includes('connection')?'verify':part?.upload&&!part.upload.commit?'upload':'publish';if(failAt===phase&&(!failOnce||!failedOnce)){failedOnce=true;const error=new Error('Failed to fetch');if(timeout)error.name='TimeoutError';throw error;}return {ok:code===200,status:code,json:async()=>{if(malformed===phase)throw new Error('Unexpected token <');return code===200?(path.includes('connection')?{site:good.site,elementor_pro:true,native_custom_fonts:true,multi_format_import:true,chunked_import:chunked,families:1,variants:1}:part?.upload&&!part.upload.commit?{received:part.upload.index+1,total:part.upload.total}:{imported:1,families:['Example']}):{message:'Reconnect'};}}}};
 context.showResult=job=>{context.activeJob=job;};vm.createContext(context);vm.runInContext(source,context);return {nodes,calls,saved,listeners};
}
(async()=>{
 let checks=0;const check=(v,msg)=>{assert(v,msg);checks++};
 let x=setup();await x.nodes['wordpress-publish'].onclick();check(x.calls.length===4,'Bundle, import and receipt');
 check(x.calls.filter(c=>c.kind==='api').every(c=>!JSON.stringify(c).includes(good.key)),'Secret never sent to Django');
 const call=x.calls.find(c=>c.kind==='wp');check(call.options.headers.Authorization==='Bearer '+good.key,'Automatic WordPress auth');check(call.options.credentials==='omit'&&call.options.redirect==='error','No cookies or redirects');check(x.nodes['wordpress-status'].textContent.includes('Published to Elementor Custom Fonts on site.example'),'Success feedback');
 for(const endpoint of ['http://site.example/wp-json/fontready/v1/fonts','https://evil.example/wp-json/fontready/v1/fonts','https://user:pass@site.example/wp-json/fontready/v1/fonts','https://site.example/elsewhere','https://site.example/wp-json/fontready/v1/fonts#secret']){x=setup({connection:{...good,endpoint}});await x.nodes['wordpress-publish'].onclick();check(!x.calls.length,'Unsafe endpoint rejected');}
 x=setup({connection:{...good,endpoint:'https://site.example/?rest_route=/fontready/v1/fonts',status:'https://site.example/?rest_route=/fontready/v1/connection'}});await x.nodes['wordpress-publish'].onclick();check(x.calls.length===4,'Query REST supported');
 x=setup({expired:true});await x.nodes['wordpress-publish'].onclick();check(!x.calls.length,'Expired kit blocked');x=setup({preview:true});await x.nodes['wordpress-publish'].onclick();check(!x.calls.length,'Preview blocked');x=setup({connection:null});await x.nodes['wordpress-publish'].onclick();check(!x.calls.length,'Connection required');
 x=setup({code:401});await x.nodes['wordpress-publish'].onclick();check(!x.saved.has('fontready.website.v3'),'Revoked connection cleared');x=setup();x.nodes['wordpress-disconnect'].onclick();check(!x.saved.has('fontready.website.v3'),'Disconnect clears credential');
 x=setup({connection:null,callback:{...good,state:'b'.repeat(64)}});await new Promise(resolve=>setImmediate(resolve));check(x.saved.has('fontready.website.v3'),'Callback confirmed and stored');check(x.calls.filter(c=>c.kind==='api').every(c=>!JSON.stringify(c).includes(good.key)),'Callback secret excluded from server');
 const id='12345678-1234-1234-1234-123456789abc';x=setup({connection:null,callback:{...good,state:'b'.repeat(64)},elementor:true,kit:id});await new Promise(resolve=>setImmediate(resolve));await new Promise(resolve=>setImmediate(resolve));check(x.calls.some(c=>c.kind==='wp'&&c.path===good.endpoint),'Selected kit automatically published after approval');check(!x.saved.has('fontready.pending-publish'),'Approval resumes only once');
 x=setup({elementor:true});await new Promise(resolve=>setImmediate(resolve));x.listeners['fontready:kit']();await new Promise(resolve=>setImmediate(resolve));check(x.calls.some(c=>c.kind==='wp'&&c.path===good.endpoint),'New upload auto-publishes to connected Elementor site');check(x.nodes['elementor-progress'].value===4,'Publishing completion updates progress');const before=x.calls.length;x.listeners['fontready:kit']();await new Promise(resolve=>setImmediate(resolve));check(x.calls.length===before,'Completed kit is not automatically published twice');
 for(const failAt of ['verify','publish']){x=setup({failAt});await x.nodes['wordpress-publish'].onclick();const text=x.nodes['wordpress-status'].textContent;check(!text.includes('Failed to fetch'),'Raw browser error is not displayed');check(text.includes('site.example'),'Error names the destination');check(x.nodes['wordpress-publish'].disabled===false,'Retry control enabled after network failure');check(x.saved.has('fontready.website.v3'),'Network failure keeps the connection for retry');if(failAt==='verify'){check(text.includes('No font files were sent'),'Verification failure distinguishes unsent font');check(!x.calls.some(c=>c.kind==='wp'&&c.path===good.endpoint),'No import after failed verification');}else{check(text.includes('may already be installed'),'Interrupted import does not claim failure to install');check(!x.nodes['elementor-manage'].hidden,'Interrupted import offers native dashboard link');}}
 x=setup({failAt:'verify',offline:true});await x.nodes['wordpress-publish'].onclick();check(x.nodes['wordpress-status'].textContent.includes('offline'),'Offline error gives internet recovery');
 x=setup({failAt:'verify',timeout:true});await x.nodes['wordpress-publish'].onclick();check(x.nodes['wordpress-status'].textContent.includes('contact'),'Timeout has contextual website recovery');
 x=setup({malformed:'publish'});await x.nodes['wordpress-publish'].onclick();check(x.nodes['wordpress-status'].textContent.includes('may already be installed'),'Malformed publishing acknowledgement requires checking native fonts');
 for(const [code,phrase] of [[401,'expired'],[403,'security'],[404,'plugin endpoint'],[413,'too large'],[429,'Wait a moment']]){x=setup({code});await x.nodes['wordpress-publish'].onclick();check(x.nodes['wordpress-status'].textContent.includes(phrase),'Actionable HTTP '+code);if(code===401){check(!x.nodes['website-confirmation'].hidden,'Expired authorization reveals reconnect form');check(x.nodes['wordpress-publish'].textContent.includes('Reconnect'),'Expired authorization relabels primary action');}}
 x=setup({chunked:true,payloadSize:1100000});await x.nodes['wordpress-publish'].onclick();
 const uploads=x.calls.filter(c=>c.kind==='wp'&&c.options.body).map(c=>JSON.parse(c.options.body));
 const parts=uploads.filter(c=>c.upload&&!c.upload.commit);check(parts.length>1,'Large package uses small upload requests');
 check(x.calls.filter(c=>c.kind==='wp'&&c.options.body).every(c=>Buffer.byteLength(c.options.body)<256*1024),'Each upload is below the live server accepted probe size');
 const assembled=Buffer.concat(parts.map(c=>Buffer.from(c.upload.data,'base64'))).toString();check(JSON.parse(assembled).padding.length===1100000,'All uploaded package bytes preserved');
 check(uploads.at(-1).upload.commit===true,'Installation only requested after all pieces');
 check(x.nodes['wordpress-status'].textContent.includes('Published'),'Chunked publication completes');
 check(x.calls.filter(c=>c.kind==='api').every(c=>!JSON.stringify(c).includes(good.key)),'Chunking keeps credential out of Django');
 x=setup({chunked:true,payloadSize:300000,failAt:'upload',failOnce:true});await x.nodes['wordpress-publish'].onclick();check(x.nodes['wordpress-status'].textContent.includes('Published'),'Lost chunk acknowledgement retried automatically');
 const retried=x.calls.filter(c=>c.kind==='wp'&&c.options.body).map(c=>JSON.parse(c.options.body));check(retried[0].upload.id===retried[1].upload.id&&retried[0].upload.index===retried[1].upload.index,'Chunk retry preserves transfer and index');
 x=setup({chunked:true,payloadSize:300000,failAt:'upload'});await x.nodes['wordpress-publish'].onclick();check(x.nodes['wordpress-status'].textContent.includes('not been submitted'),'Upload interruption distinguishes no installation');check(!x.calls.some(c=>c.options?.body&&JSON.parse(c.options.body).upload?.commit),'Incomplete upload never committed');
 x=setup({payloadSize:300000});await x.nodes['wordpress-publish'].onclick();check(x.nodes['wordpress-status'].textContent.includes('0.4.2'),'Older plugin requires update for large package');check(!x.calls.some(c=>c.kind==='wp'&&c.options.body),'Large package not sent to old plugin');
 const app=fs.readFileSync('static/app.js','utf8');const apiSource=app.slice(app.indexOf('async function api('),app.indexOf('function updateButton('));
 for(const sample of [{network:true,phrase:'Could not reach FontReady'},{status:403,phrase:'session'},{status:413,phrase:'too large'},{status:429,phrase:'busy'},{status:503,phrase:'could not complete'},{status:200,malformed:true,phrase:'unexpected response'}]){const apiContext={fetch:async()=>{if(sample.network)throw new Error('Failed to fetch');return {ok:sample.status===200,status:sample.status,json:async()=>{if(sample.malformed)throw new Error('Unexpected token');return {};}}},Error};vm.createContext(apiContext);vm.runInContext(apiSource,apiContext);try{await apiContext.api('/api/conversions/');check(false,'Error expected');}catch(error){check(error.message.includes(sample.phrase),'FontReady request has actionable error');check(!error.message.includes('Failed to fetch'),'FontReady hides raw browser transport error');}}
 const order=[];const callbackContext={location:{hash:'#fontready='+encodeURIComponent(JSON.stringify(good)),pathname:'/font-to-elementor-pro/',search:''},history:{replaceState(){order.push('stripped')}},window:{},JSON,decodeURIComponent};vm.runInNewContext(fs.readFileSync('static/wordpress-callback.js','utf8'),callbackContext);check(order[0]==='stripped'&&callbackContext.window.fontreadyCallback.key===good.key,'Fragment stripped synchronously');
 console.log(`Passed ${checks} seamless publishing UI contract checks.`);
})().catch(e=>{console.error(e);process.exit(1)});
